# Generated by Django 2.1.7 on 2019-03-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodstype',
            table='offtake_goods_type',
        ),
    ]
